services:
  # SSL Provider services
  ims-ssl-nginx:
    profiles: ["ssl"]
    build:
      context: ./sslProvider
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ims-ssl-nginx
    ports:
      - 8080:80
    volumes:
      - certbot-www:/var/www/certbot
    networks:
      - ims-base-network

  ims-certbot:
    profiles: ["ssl"]
    image: certbot/certbot
    volumes:
      - ssl-certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email your@email.com -d ims-mts.ru -d www.ims-mts.ru --agree-tos --no-eff-email --force-renewal
    depends_on:
      - ims-ssl-nginx
    healthcheck:
      test: ["CMD", "test", "-f", "/etc/letsencrypt/live/ims-mts.ru/fullchain.pem"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - ims-base-network

  # Main application services
  ims-nginx:
    profiles: ["app"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ims-nginx
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./frontend/.env
    volumes:
      - ssl-certs:/etc/nginx/ssl
    networks:
      - ims-base-network

  ims-backend:
    profiles: ["app"]
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    container_name: ims-backend
    env_file:
    #  - ./.env/.backend.development.env
      - ./.env/.backend.prod.env
    networks:
      - ims-base-network

  ims-keycloak:
    profiles: ["app"]
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    container_name: ims-keycloak
    env_file:
    #  - ./.env/.keycloak.development.env
      - ./.env/.keycloak.prod.env
    volumes:
      - ./keycloak:/opt/keycloak/conf
      - ssl-certs:/opt/keycloak/certs
    ports:
      - 8087:8087
    command: start --https-certificate-file=/opt/keycloak/certs/live/ims-mts.ru/fullchain.pem --https-certificate-key-file=/opt/keycloak/certs/live/ims-mts.ru/privkey.pem --http-enabled=true
    depends_on:
      - ims-keycloak-db
    networks:
      - ims-base-network

  ims-keycloak-db:
    profiles: ["app"]
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: ims-keycloak-db
    env_file:
      - ./.env/.keycloak.prod.env
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - ims-base-network

  ims-postgres:
    profiles: ["app"]
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env/.postgres.prod.env
    volumes:
      - iml-db-data:/var/lib/postgresql/data
    networks:
      - ims-base-network

  ims-pgadmin:
    profiles: ["app"]
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: ims-pgadmin
    env_file:
      - ./.env/.pgadmin.development.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - ims-base-network
    depends_on:
      - ims-postgres

volumes:
  ssl-certs:
  certbot-www:
  keycloak-db-data:
  iml-db-data:
  pgadmin-data:

networks:
  ims-base-network:
    driver: bridge
