services:
  # nginx:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #   env_file:
  #     - ./frontend/.env
  #   networks:
  #     - ims-base-network

  # rag_mongodb:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   container_name: mongodb_rag
  #   expose:
  #     - '27018'
  #   volumes:
  #     - mongodb_rag_data:/data/db
  #     - ./mongo/mongo.conf:/etc/mongo/mongo.conf
  #   command: mongod --config etc/mongo/mongo.conf
  #   env_file:
  #     - ./.env/.development.env
  #   networks:
  #     - lt-base-network

  # rag_chroma:
  #   image: chromadb/chroma
  #   restart: unless-stopped
  #   container_name: chroma_container
  #   expose:
  #     - '8001'
  #   env_file:
  #     - ./.env/.development.env
  #   volumes:
  #     - chroma_data:/chroma
  #   networks:
  #     - lt-base-network
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:8001/docs" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    container_name: keycloak
    env_file:
      - ./.env/.keycloak.development.env
    volumes:
      - ./keycloak:/opt/keycloak/conf
    ports:
      - "8087:8087"
    command: [ "start-dev", "--http-port=8087" ]
    depends_on:
      - keycloak-db
    networks:
      - ims-base-network

  keycloak-db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: keycloak-db
    env_file:
      - ./.env/.keycloak.development.env
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - ims-base-network

  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env/.postgres.development.env
    volumes:
      - iml-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ims-base-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin
    env_file:
      - ./.env/.pgadmin.development.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - ims-base-network
    depends_on:
      - postgres

volumes:
  keycloak-db-data:
  iml-db-data:
  pgadmin-data:

networks:
  ims-base-network:
    driver: bridge
