services:
  ims-nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ims-nginx
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./frontend/.env
    volumes:
      - ssl-certs:/etc/nginx/ssl
    depends_on:
      certbot:
        condition: service_healthy
    networks:
      - ims-base-network

  ims-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    container_name: ims-backend
    env_file:
    #  - ./.env/.backend.development.env
      - ./.env/.backend.prod.env
    networks:
      - ims-base-network

  ims-keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    container_name: ims-keycloak
    env_file:
    #  - ./.env/.keycloak.development.env
      - ./.env/.keycloak.prod.env
    volumes:
      - ./keycloak:/opt/keycloak/conf
    ports:
      - "8087:8087"
    command: [ "start-dev", "--http-port=8087" ]
    depends_on:
      - ims-keycloak-db
    networks:
      - ims-base-network

  ims-keycloak-db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: ims-keycloak-db
    env_file:
      - ./.env/.keycloak.prod.env
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - ims-base-network

  ims-postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env/.postgres.prod.env
    volumes:
      - iml-db-data:/var/lib/postgresql/data
    networks:
      - ims-base-network

  ims-pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: ims-pgadmin
    env_file:
      - ./.env/.pgadmin.development.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - ims-base-network
    depends_on:
      - ims-postgres

  certbot:
    image: certbot/certbot
    volumes:
      - ssl-certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email your@email.com -d ims-mts.ru -d www.ims-mts.ru --agree-tos --no-eff-email
    healthcheck:
      test: ["CMD", "test", "-f", "/etc/letsencrypt/live/ims-mts.ru/fullchain.pem"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  ssl-certs:
  keycloak-db-data:
  iml-db-data:
  pgadmin-data:

networks:
  ims-base-network:
    driver: bridge
