export enum ERoutes {
  HOME = "/",
  INCIDENTS_LIST = "/incidents",
  INCIDENT = "/incidents/:id",
  INCIDENT_CREATE = "/incidents/edit",
  INCIDENT_EDIT = "/incidents/edit/:id",
  INCIDENT_VIEW = "/incidents/view",
  INCIDENT_VIEW_ID = "/incidents/view/:id",
  OPERATIONAL_ACTIVITY = "/operational-activities/:id",
  OPERATIONAL_ACTIVITY_CREATE = "/operational-activities/edit",
  OPERATIONAL_ACTIVITY_EDIT = "/operational-activities/edit/:id",
  OPERATIONAL_ACTIVITY_VIEW = "/operational-activities/view",
  OPERATIONAL_ACTIVITY_VIEW_ID = "/operational-activities/view/:id",
  OPERATIONAL_ACTIVITIES_LIST = "/operational-activities",
  PROFILE = "/profile",
  DEPARTMENTS = "/departments",
  INCIDENT_EVENTS = "/incident-events",
  OBJECT_TYPES = "/object-types",
  REFERENCES = "/references",
  EVENTS_LIST = "/events",
  EVENT = "/events/:id",
  EVENT_CREATE = "/events/edit",
  EVENT_EDIT = "/events/edit/:id",
  EVENT_VIEW = "/events/view",
  EVENT_VIEW_ID = "/events/view/:id",
  REPORTS = "/reports",
  REPORT_GENERATOR = "/reports/generator",
  EXPLANATORY_NOTES_LIST = "/explanatory-notes",
}

