# Prod-only overrides (make prod). Подключается поверх docker-compose.yaml
services:
  ims-backend:
    extra_hosts:
      - "${APP_DOMAIN}:host-gateway"

  ims-keycloak:
    environment:
      - KC_PROXY_HEADERS=${KC_PROXY_HEADERS}
      - KC_HTTP_RELATIVE_PATH=${KC_HTTP_RELATIVE_PATH}
      - KC_HTTP_ENABLED=${KC_HTTP_ENABLED}
