server {
    listen 80;
    listen [::]:80;
    server_name ims-mts.ru www.ims-mts.ru;

    # Для Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Все остальные запросы возвращают 404
    location / {
        return 404;
    }
} 