server {
    # listen 443 ssl http2;
    # listen [::]:443 ssl http2;
    listen 80;
    listen [::]:80;

    # server_name base.ltspace.ru;

    # ssl_certificate /etc/letsencrypt/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/privkey.pem;

    client_max_body_size 100M; # Устанавливаем лимит на 100 МБ

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }





    # Проксирование запросов к API
    # location /apigw/ {
    #     rewrite ^/apigw(/.*)$ $1 break;
    #     proxy_pass http://apigw:8086;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;

    #     # Отключаем буферизацию для SSE
    #     proxy_buffering off;
    #     proxy_cache off;
    #     proxy_http_version 1.1;
    #     proxy_set_header Connection "";

    #     # Разрешить CORS
    #     add_header Access-Control-Allow-Origin https://base.ltspace.ru;
    #     add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
    #     add_header Access-Control-Allow-Headers "Authorization, Content-Type";
    #     add_header Access-Control-Allow-Credentials "true";
    #     if ($request_method = OPTIONS) {
    #         add_header Access-Control-Max-Age 1728000;
    #         add_header Content-Type "text/plain charset=UTF-8";
    #         add_header Content-Length 0;
    #         return 204;
    #     }
    # }
}

# Редирект с HTTP на HTTPS
# server {
#     listen 80;
#     listen [::]:80;

#     # server_name base.ltspace.ru; # Здесь можно указать ваш домен

#     # return 301 https://$host$request_uri; # Перенаправление с HTTP на HTTPS
# }